import { copyFile, mkdir, rm } from "node:fs/promises";

await rm("dist", { recursive: true, force: true });
await mkdir("dist", { recursive: true });
await copyFile("src/action-body.js", "dist/action-body.js");
await copyFile("src/action-else-block.js", "dist/action-else-block.js");
await copyFile("src/action-for-in-block.js", "dist/action-for-in-block.js");
await copyFile("src/action-repeat-block.js", "dist/action-repeat-block.js");
await copyFile("src/action-expression.js", "dist/action-expression.js");
await copyFile("src/action-expression-semantics.js", "dist/action-expression-semantics.js");
await copyFile("src/action-expression-tokenizer.js", "dist/action-expression-tokenizer.js");
await copyFile("src/action-match-block.js", "dist/action-match-block.js");
await copyFile("src/action-source-blocks.js", "dist/action-source-blocks.js");
await copyFile("src/action-syntax-children.js", "dist/action-syntax-children.js");
await copyFile("src/application-surface.js", "dist/application-surface.js");
await copyFile("src/constraint-space.js", "dist/constraint-space.js");
await copyFile("src/conversion-constraint-record.js", "dist/conversion-constraint-record.js");
await copyFile("src/conversion-metadata.js", "dist/conversion-metadata.js");
await copyFile("src/conversion.js", "dist/conversion.js");
await copyFile("src/canvas-surface.js", "dist/canvas-surface.js");
await copyFile("src/decision-graph.js", "dist/decision-graph.js");
await copyFile("src/dialect-registry.js", "dist/dialect-registry.js");
await copyFile("src/index.js", "dist/index.js");
await copyFile("src/index.d.ts", "dist/index.d.ts");
await copyFile("src/interlingua.js", "dist/interlingua.js");
await copyFile("src/metadata.js", "dist/metadata.js");
await copyFile("src/operations.js", "dist/operations.js");
await copyFile("src/package-manifest.js", "dist/package-manifest.js");
await copyFile("src/paradigm.js", "dist/paradigm.js");
await copyFile("src/proof.js", "dist/proof.js");
await copyFile("src/resource-graph.js", "dist/resource-graph.js");
await copyFile("src/runtime-capability.js", "dist/runtime-capability.js");
await copyFile("src/runtime-capability-records.js", "dist/runtime-capability-records.js");
await copyFile("src/source-block-kinds.js", "dist/source-block-kinds.js");
await copyFile("src/source-evidence.js", "dist/source-evidence.js");
await copyFile("src/source-syntax-children.js", "dist/source-syntax-children.js");
await copyFile("src/source-syntax-row-config.js", "dist/source-syntax-row-config.js");
await copyFile("src/source-syntax-report.js", "dist/source-syntax-report.js");
await copyFile("src/target-projection.js", "dist/target-projection.js");
await copyFile("src/target-projection-aggregate.js", "dist/target-projection-aggregate.js");
await copyFile("src/type-expressions.js", "dist/type-expressions.js");
await copyFile("src/type-parameters.js", "dist/type-parameters.js");
await copyFile("src/type-variants.js", "dist/type-variants.js");
await copyFile("src/view.js", "dist/view.js");
